# .github/FUNDING.yml

# GitHub Sponsors profile (recommended, uses your username)
github: kash-pram

# Custom links for other platforms (e.g., PayPal.me)
# IMPORTANT: Replace "https://paypal.me/YourActualUsername" with your link
custom:
  - "https://paypal.me/PrakashMariappan"
  - "https://razorpay.me/@kash-pram"
